// Extract the on-screen text of every scene (in DOM order) -> docs/script.md
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1920, height: 1080 } });
await p.goto('file://' + resolve(ROOT, 'src/index.html'));
await p.waitForFunction(() => window.READY === true);
const data = await p.evaluate(() => window.CUES.map((c) => {
  const root = document.getElementById('scene-' + c.id);
  const seen = new Set(), lines = [];
  // Block-level text: divs without div children, plus SVG <text>.
  root.querySelectorAll('div, text').forEach((el) => {
    if (el.tagName === 'DIV' && el.querySelector('div')) return;
    const cl = el.cloneNode(true); cl.querySelectorAll && cl.querySelectorAll('br').forEach((br) => br.replaceWith(' '));
    const t = (cl.textContent || '').replace(/\s+/g, ' ').trim();
    if (!t || t === 'undefined' || seen.has(t) || el.style.display === 'none') return;
    seen.add(t); lines.push(t);
  });
  return { id: c.id, start: c.start, duration: c.duration, chapter: c.chapter, lines };
}));
await b.close();
const fmt = (s) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`;
let md = '# On-screen script (extracted from the final scenes)\n\nThis is generated by `node render/script.mjs`. It lists every piece of text that appears in each scene, in DOM order.\n\n';
for (const d of data) {
  md += `## ${fmt(d.start)} · ${d.id}${d.chapter ? ` (Ch${d.chapter.n} ${d.chapter.title})` : ''} · ${d.duration}s\n\n`;
  md += d.lines.map((l) => `- ${l}`).join('\n') + '\n\n';
}
writeFileSync(resolve(ROOT, 'docs/script.md'), md);
console.log('wrote docs/script.md', data.length, 'scenes');
