// Regenerate src/shots/manifest.js from the numbered shot files (NNN-id.js), in order, and check them
// against docs/shotlist.json (missing / unexpected shots).   node render/manifest.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ROOT } from './browser.mjs';
const dir = resolve(ROOT, 'src/shots');
const files = readdirSync(dir).filter((f) => /^\d{3}-.+\.js$/.test(f)).sort();
writeFileSync(resolve(dir, 'manifest.js'), `// generated by render/manifest.mjs\nexport default ${JSON.stringify(files, null, 1)};\n`);
const list = JSON.parse(readFileSync(resolve(ROOT, 'docs/shotlist.json'), 'utf8')).shots;
const want = list.map((s) => `${String(s.n).padStart(3, '0')}-${s.id}.js`);
const missing = want.filter((f) => !files.includes(f)), extra = files.filter((f) => !want.includes(f));
console.log(`${files.length} shot files in manifest; ${missing.length} missing, ${extra.length} unexpected`);
if (missing.length) console.log('missing:', missing.join(' '));
if (extra.length) console.log('unexpected:', extra.join(' '));
